version: '3'
services:
  frontend:
    build:
      context: ./frontend
    platform: linux/amd64
    tty: true # docker run -t
    stdin_open: true # docker run -i
    ports:
      - "8000:8000"
    env_file: config.env
    environment:
      - VITE_API_URL=http://backend:8001
    volumes:
      - ./frontend:/app
    command: sh -c "chmod +x start.sh && ./start.sh"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    platform: linux/amd64
    tty: true
    stdin_open: true
    ports:
      - "8001:8001"
    env_file: config.env
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_PORT=8001
      - PYTHONPATH=/main
    volumes:
      - ./backend:/main
    command: sh -c "chmod +x start.sh && ./start.sh"
